// auth-core.js V4 Final - No Emoji - MagnetraPH - Fingerprint Eyeblink FAQ Google
(function(){
var lastBackTap=0;
function showStatus(m){var s=document.getElementById('status');if(s) s.textContent=m;}
function shakeField(id){var el=document.getElementById(id);if(!el) return;el.classList.remove('shake');void el.offsetWidth;el.classList.add('shake');el.classList.add('error');setTimeout(function(){el.classList.remove('error');},900);}
function shakeBoth(){shakeField('emailField');shakeField('passField');}
function goPage(e,url){if(e) e.preventDefault();var card=document.getElementById('card');if(card) card.classList.add('page-exit');setTimeout(function(){location.href=url;},350);return false;}
function animateContent(id){var el=document.getElementById(id);if(!el) return;el.classList.remove('active');el.style.display='block';void el.offsetWidth;setTimeout(function(){el.classList.add('active');},20);}
function openHelp(){var hc=document.getElementById('helpContent');var fc=document.getElementById('forgotContent');if(hc) hc.style.display='block';if(fc){fc.style.display='none';fc.classList.remove('active');}var sheet=document.getElementById('sheet');if(sheet) sheet.classList.add('open');animateContent('helpContent');}
function openForgot(){var hc=document.getElementById('helpContent');var fc=document.getElementById('forgotContent');if(hc){hc.style.display='none';hc.classList.remove('active');}if(fc) fc.style.display='block';var sheet=document.getElementById('sheet');if(sheet) sheet.classList.add('open');var em=document.getElementById('email');var re=document.getElementById('resetEmail');if(em&&re) re.value=em.value;animateContent('forgotContent');}
function closeSheet(){var box=document.getElementById('sheetBox');var sheet=document.getElementById('sheet');if(!box||!sheet) return;box.style.transform='translateY(100%)';setTimeout(function(){sheet.classList.remove('open');box.style.transform='';var hc=document.getElementById('helpContent');var fc=document.getElementById('forgotContent');if(hc) hc.classList.remove('active');if(fc) fc.classList.remove('active');},300);}
function toggleEye(){try{var p=document.getElementById('password');var g=document.getElementById('eyeGroup');if(!p||!g) return;g.classList.remove('blink-open','blink-close');void g.getBoundingClientRect();g.classList.add('blink-close');setTimeout(function(){p.type=p.type==='password'?'text':'password';var isText=p.type==='text';var svg=document.getElementById('eyeSvg');if(!svg) return;if(isText){svg.innerHTML='<g id="eyeGroup" class="blink-open"><path d="M2 12s3-7 10-7s10 7 10 7s-3 7-10 7s-10 7s-10-7s-10-7-10-7Z"/><path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0-6 0"/><path d="M3 3l18 18"/></g>';}else{svg.innerHTML='<g id="eyeGroup" class="blink-open"><path d="M1 12s4-7 11-7s11 7 11 7s-4 7-11 7s-11-7-11-7z"/><circle cx="12" cy="12" r="3.5"/></g>';}},120);}catch(e){}}
async function sendReset(){var emailEl=document.getElementById('resetEmail');var rs=document.getElementById('resetStatus');var email=emailEl?emailEl.value.trim().toLowerCase():'';if(!email){if(rs) rs.innerText='Enter email first';shakeField('resetField');return;}if(window.LoginSecurity){var chk=LoginSecurity.canAttempt(email);if(!chk.ok){if(rs) rs.innerText=chk.msg;return;}}if(rs) rs.innerText='Sending...';try{if(typeof auth==="undefined"){if(rs) rs.innerText='Auth not ready';return;}await auth.sendPasswordResetEmail(email);if(rs) rs.innerText='Reset link sent! Check inbox.';}catch(err){if(window.LoginSecurity) LoginSecurity.addFail(email);if(rs) rs.innerText='Unable to send';}}
async function login(){var start=Date.now();var emailEl=document.getElementById('email');var passEl=document.getElementById('password');var btn=document.getElementById('btnLogin');var email=emailEl?emailEl.value.trim().toLowerCase():'';var pwd=passEl?passEl.value:'';if(window.LoginSecurity&&LoginSecurity.isBot()){showStatus('Blocked');return;}if(!email||email.indexOf('@')<1){shakeField('emailField');showStatus('Invalid email');return;}if(!pwd){shakeField('passField');showStatus('Enter password');return;}if(window.LoginSecurity){var chk=LoginSecurity.canAttempt(email);if(!chk.ok){showStatus(chk.msg);return;}}if(btn){btn.disabled=true;btn.innerText='Logging in...';}showStatus('Logging in...');try{if(typeof auth==="undefined") throw new Error('no auth');var cred=await auth.signInWithEmailAndPassword(email,pwd);if(window.LoginSecurity) LoginSecurity.clearFail(email);try{await db.collection('users').doc(cred.user.uid).set({lastLogin: firebase.firestore.FieldValue.serverTimestamp(),lastDevice: LoginSecurity.getDeviceId()},{merge:true});}catch(e){}var d=window.LoginSecurity?LoginSecurity.constantDelay(start):0;setTimeout(function(){goPage(null,'dashboard.html');},d);}catch(e){if(window.LoginSecurity) LoginSecurity.addFail(email);var d2=window.LoginSecurity?LoginSecurity.constantDelay(start):0;setTimeout(function(){showStatus('Invalid email or password');shakeBoth();if(btn){btn.disabled=false;btn.innerText='Log in';}},d2);}}
async function loginGoogle(){var start=Date.now();if(window.LoginSecurity){var chk=LoginSecurity.canAttempt('google');if(!chk.ok){showStatus(chk.msg);return;}}showStatus('Connecting...');try{if(typeof auth==="undefined") throw new Error('no auth');var provider=new firebase.auth.GoogleAuthProvider();var cred=await auth.signInWithPopup(provider);var d=window.LoginSecurity?LoginSecurity.constantDelay(start):0;setTimeout(function(){goPage(null,'dashboard.html');},d);}catch(e){var d2=window.LoginSecurity?LoginSecurity.constantDelay(start):0;setTimeout(function(){showStatus('Unable to continue with Google');},d2);}}
function loginBio(){showStatus('Biometrics not yet enrolled');}
function bindAll(){
var eyeBtn=document.getElementById('eyeBtn');if(eyeBtn) eyeBtn.onclick=toggleEye;
var btnLogin=document.getElementById('btnLogin');if(btnLogin) btnLogin.onclick=login;
var btnBio=document.getElementById('btnBio');if(btnBio) btnBio.onclick=loginBio;
var btnGoogle=document.getElementById('btnGoogle');if(btnGoogle) btnGoogle.onclick=loginGoogle;
var forgotLink=document.getElementById('forgotLink');if(forgotLink) forgotLink.onclick=openForgot;
var helpLink=document.getElementById('helpLink');if(helpLink) helpLink.onclick=openHelp;
var closeHelp=document.getElementById('closeHelp');if(closeHelp) closeHelp.onclick=closeSheet;
var closeForgot=document.getElementById('closeForgot');if(closeForgot) closeForgot.onclick=closeSheet;
var btnSend=document.getElementById('btnSendReset');if(btnSend) btnSend.onclick=sendReset;
var createLink=document.getElementById('createLink');if(createLink) createLink.onclick=function(e){goPage(e,'create.html');};
var sheet=document.getElementById('sheet');if(sheet) sheet.addEventListener('click',function(e){if(e.target.id==='sheet') closeSheet();});
}
if(document.readyState==="loading"){document.addEventListener('DOMContentLoaded',bindAll);}else{bindAll();}
})();
